apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-service
  ports:
    - protocol: TCP
      port: 33065
      targetPort: 33065
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
        - name: spring-service
          image: camranjuntinase/sa_pr:proyectosa_backend
          ports:
            - containerPort: 33065

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
        - name: mysql-service
          image: camranjuntinase/sa_pr:mysql_ticketsys
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-service
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:
        - name: react-service
          image: camranjuntinase/sa_pr:proyectosa_frontendVV1
          ports:
            - containerPort: 5173

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: "nginx"
  rules:
    - host: tikcetsys-asd.xyz  # Aquí se especifica el host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-service
                port:
                  number: 5173


          
