name: SA_Project CI

on:
  push:
    branches:
      - feature/*
    
jobs:
  build_stage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 21.7.0
        java-version:
          - 17

    steps:
      - name: Checkout and copy code to workflow
        uses: actions/checkout@v2

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      #  Configurar microservicios
      - name: Install and Build Microservice frontend
        run: |
          cd ProyectoSA_frontend/
          npm install

      - name: Install and Build Microservice tickets
        run: |
          cd ProyectoSA_backend/
          mvn clean install -U
          mvn clean package
          mvn clean test jacoco:report
    
      - name: Publish JaCoCo report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: ProyectoSA_backend/target/site/jacoco
